name: github pages

on:
  push:
    branches:
      - master
      - main
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    name: deploy to github pages
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@main
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up
        run: sudo apt-get update -y && sudo apt install -y git clang curl libssl-dev llvm libudev-dev graphviz
      
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          default: true
      
      - name: Set up Cargo Bin Install
        run: |
          export PATH="$PATH:$HOME/.cargo/bin"
          wget https://github.com/ryankurte/cargo-binstall/releases/latest/download/cargo-binstall-x86_64-unknown-linux-gnu.tgz
          tar xf cargo-binstall-x86_64-unknown-linux-gnu.tgz --directory=$HOME/.cargo/bin
      
      - name: Set up Cache
        uses: Swatinem/rust-cache@v1
      
      - name: cargo install mdbook tools
        run: |
          cargo-binstall mdbook --no-confirm
          cargo-binstall mdbook-linkcheck --no-confirm
          cargo-binstall mdbook-graphviz --no-confirm
          cargo-binstall mdbook-mermaid --no-confirm

      # - name: Setup mdBook
      #   uses: peaceiris/actions-mdbook@v1
      #   with:
      #     mdbook-version: 'latest'

      - name: Build mdBook
        run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book